# Generated by Django 2.2.7 on 2020-11-10 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(null=True)),
                ('poster_url', models.TextField(null=True)),
                ('release_date', models.CharField(max_length=30, null=True)),
                ('runningtime', models.CharField(max_length=10, null=True)),
                ('rating', models.TextField(null=True)),
                ('genres', models.CharField(max_length=255, null=True)),
                ('actors', models.TextField(null=True)),
                ('nation', models.CharField(max_length=255, null=True)),
                ('maker', models.CharField(max_length=255, null=True)),
                ('director', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tagdatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=30, null=True)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_tagdatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('tagdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.tagdatas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='tagdatas',
            field=models.ManyToManyField(null=True, related_name='movie_tagdatas', to='movies.tagdatas'),
        ),
    ]
