# Generated by Django 2.2.7 on 2020-11-08 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tagdatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('poster_url', models.TextField(blank=True)),
                ('release_date', models.CharField(blank=True, max_length=30)),
                ('runningtime', models.CharField(blank=True, max_length=10)),
                ('rating', models.TextField(blank=True)),
                ('genres', models.CharField(blank=True, max_length=255)),
                ('actors', models.TextField(blank=True)),
                ('nation', models.CharField(blank=True, max_length=255)),
                ('maker', models.CharField(blank=True, max_length=255)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('tagdatas', models.ManyToManyField(blank=True, related_name='movie_tagdatas', to='movies.tagdatas')),
            ],
        ),
        migrations.CreateModel(
            name='User_Movie_cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('movie_cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie_cast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movie_casts', to='movies.Movie_cast'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='movie_genre', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview_tags',
            field=models.ManyToManyField(null=True, related_name='overview_tags', to='movies.Overview_tag'),
        ),
    ]
