# Generated by Django 2.2.7 on 2020-11-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_actors', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.CharField(max_length=255, null=True)),
                ('release_date', models.CharField(max_length=30, null=True)),
                ('runningtime', models.CharField(max_length=10, null=True)),
                ('rating', models.CharField(max_length=11, null=True)),
                ('nation', models.CharField(max_length=255, null=True)),
                ('maker', models.CharField(max_length=255, null=True)),
                ('director', models.CharField(max_length=255, null=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='movie_casts', to='movies.Movie_cast')),
            ],
        ),
    ]
