# Generated by Django 2.2.7 on 2020-11-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagdatas',
            name='weight',
        ),
    ]
